package com.sddrozdov.doska.constans

object FirebaseAuthConstants {
    const val ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE"
    const val ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
    const val ERROR_WEAK_PASSWORD = "ERROR_WEAK_PASSWORD"
    const val ERROR_INVALID_CREDENTIAL = "ERROR_INVALID_CREDENTIAL"
    const val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"

}